migrate sprintf to null-safety
Naddiseo/dart-sprintf pull request #25
Opened 2020-12-09 16:28 UTC by vishna

closes #24

2020-12-09 22:09 UTC, vishna commented
CI fails on stable which is __expected__ because of the dart version.

2020-12-09 23:29 UTC, Naddiseo requested changes
Thanks for the PR, mostly looks good, two other files need changing:
1. Could you update .travil.yml to replace "stable" with "beta"
2. Could you add an entry into the CHANGELOG file

thanks!

2020-12-09 23:29 UTC, Naddiseo commented on lib/src/formatters/Formatter.dart
> +  String? asString();
I don't think this change is needed

2020-12-09 23:29 UTC, Naddiseo commented on lib/src/formatters/float_formatter.dart
> +  String? asString() {
This change isn't needed. The `_output` var has a direct null check before it's returned, so the line can be changed to ` return _output!;`

2020-12-09 23:29 UTC, Naddiseo commented on lib/src/sprintf_impl.dart
> +        _arg_str = _formatters[_type]!(_arg, _options).asString()!;
```suggestion
        _arg_str = _formatters[_type]!(_arg, _options).asString();
```

2020-12-10 14:42 UTC, vishna commented
updated my PR

2020-12-10 15:55 UTC, merged